In [1]:
import pandas as pd

data = {
        'Valore': [10, 5, 8, 12, 3],
        'Quantità': [20, 15, 10, 25, 5],
        'Testo': ['abc', 'def', 'ghi', 'jkl', 'mno'],
        'Categoria': ['A', 'B', 'A', 'C', 'B'],
        'ID': [1, 2, 3, 4, 1],
        'Descrizione': ['desc1 importante', 'desc2', 'desc3', 'desc4 importante', 'desc5']
        }

df = pd.DataFrame(data)
df

   Valore  Quantità Testo Categoria  ID       Descrizione
0      10        20   abc         A   1  desc1 importante
1       5        15   def         B   2             desc2
2       8        10   ghi         A   3             desc3
3      12        25   jkl         C   4  desc4 importante
4       3         5   mno         B   1             desc5

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Valore       5 non-null      int64
 1   Quantità     5 non-null      int64
 2   Testo        5 non-null      object
 3   Categoria    5 non-null      object
 4   ID           5 non-null      int64
 5   Descrizione  5 non-null      object
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes

In [3]:
def doppio(x):
    return x*2

In [4]:
df['Valore'].apply(doppio)

0    20
1    10
2    16
3    24
4     6
Name: Valore, dtype: int64

In [5]:
df['Valore'].apply(lambda x: x *2)

0    20
1    10
2    16
3    24
4     6
Name: Valore, dtype: int64

In [6]:
## Creare una nuova colonna in un DataFrame chiamata "Doppio_Valore" che contenga il doppio del valore della colonna esistente "Valore".
df['Doppio_Valore'] = df['Valore'].apply(lambda x: x * 2)
df

   Valore  Quantità Testo Categoria  ID       Descrizione  Doppio_Valore
0      10        20   abc         A   1  desc1 importante             20
1       5        15   def         B   2             desc2             10
2       8        10   ghi         A   3             desc3             16
3      12        25   jkl         C   4  desc4 importante             24
4       3         5   mno         B   1             desc5              6

In [14]:
#Filtrare le righe di un DataFrame in base a una condizione, ad esempio, ottenere solo le righe con valori superiori a 3 nella colonna "Valore".
df[df['Valore'].apply(lambda x: x > 3)]

   Valore  Quantità Testo Categoria  ID       Descrizione  Doppio_Valore
0      10        20   ABC         A   1  desc1 importante             20
1       5        15   DEF         B   2             desc2             10
2       8        10   GHI         A   3             desc3             16
3      12        25   JKL         C   4  desc4 importante             24

In [8]:
#Applicare una lambda function alla colonna "Testo" per convertire tutti i valori in maiuscolo.
df['Testo'] = df['Testo'].apply(lambda x: x.upper())
df

   Valore  Quantità Testo Categoria  ID       Descrizione  Doppio_Valore
0      10        20   ABC         A   1  desc1 importante             20
1       5        15   DEF         B   2             desc2             10
2       8        10   GHI         A   3             desc3             16
3      12        25   JKL         C   4  desc4 importante             24
4       3         5   MNO         B   1             desc5              6

In [11]:
#Contare quante volte compare ciascun valore nella colonna "Categoria".

conteggio_categorie = df.groupby(lambda x: df.loc[x, 'Categoria']).size().reset_index()
conteggio_categorie.columns = ['Categoria', 'Conteggio']
conteggio_categorie

  Categoria  Conteggio
0         A          2
1         B          2
2         C          1

In [12]:
#Rinominare tutte le colonne di un DataFrame aggiungendo il prefisso "Nuovo_".
df.rename(columns=lambda x: f'Nuovo_{x}')

,Nuovo_Valore,Nuovo_Quantità,Nuovo_Testo,Nuovo_Categoria,Nuovo_ID,Nuovo_Descrizione,Nuovo_Doppio_Valore
0,10,20,ABC,A,1,desc1 importante,20
1,5,15,DEF,B,2,desc2,10
2,8,10,GHI,A,3,desc3,16
3,12,25,JKL,C,4,desc4 importante,24
4,3,5,MNO,B,1,desc5,6

In [12]:
#Applicare una funzione a tutte le colonne:
df.apply(lambda col: col.sum())

Valore                                                        38
Quantità                                                      75
Testo                                            ABCDEFGHIJKLMNO
Categoria                                                  ABACB
ID                                                            11
Descrizione      desc1 importantedesc2desc3desc4 importantedesc5
Doppio_Valore                                                 76
dtype: object

In [13]:
#Ordinare il DataFrame in base alla colonna "Valore" in ordine decrescente.

df.sort_values(by='Valore', ascending=False)

   Valore  Quantità Testo Categoria  ID       Descrizione  Doppio_Valore
3      12        25   JKL         C   4  desc4 importante             24
0      10        20   ABC         A   1  desc1 importante             20
2       8        10   GHI         A   3             desc3             16
1       5        15   DEF         B   2             desc2             10
4       3         5   MNO         B   1             desc5              6

In [14]:
#Creare una nuova colonna "Totale" che rappresenti la somma di "Valore" e "Quantità".

df['Totale'] = df.apply(lambda row: row['Valore'] + row['Quantità'], axis=1)
df

,Valore,Quantità,Testo,Categoria,ID,Descrizione,Doppio_Valore,Totale
0,10,20,ABC,A,1,desc1 importante,20,30
1,5,15,DEF,B,2,desc2,10,20
2,8,10,GHI,A,3,desc3,16,18
3,12,25,JKL,C,4,desc4 importante,24,37
4,3,5,MNO,B,1,desc5,6,8

In [15]:
#Rimuovere le righe duplicate basandosi sulla colonna "ID".
df.drop_duplicates(subset='ID')

,Valore,Quantità,Testo,Categoria,ID,Descrizione,Doppio_Valore,Totale
0,10,20,ABC,A,1,desc1 importante,20,30
1,5,15,DEF,B,2,desc2,10,20
2,8,10,GHI,A,3,desc3,16,18
3,12,25,JKL,C,4,desc4 importante,24,37

In [17]:
#Filtrare le righe del DataFrame in cui la colonna "Descrizione" contiene la parola "importante".
df[df['Descrizione'].apply(lambda x: 'importante' in x.lower())]

,Valore,Quantità,Testo,Categoria,ID,Descrizione,Doppio_Valore,Totale
0,10,20,ABC,A,1,desc1 importante,20,30
3,12,25,JKL,C,4,desc4 importante,24,37